# Cloudflare Workers configuration
name = "myportfolio"
compatibility_date = "2023-12-01"
pages_build_output_dir = "dist"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "myportfolio"
preview_bucket_name = "myportfolio"
