# Cloudflare Workers configuration
name = "myportfolio"
main = "functions/_middleware.js"
compatibility_date = "2023-12-01"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "myportfolio"
preview_bucket_name = "myportfolio"
