name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Create Pages-specific wrangler.toml
        run: |
          echo "# Cloudflare Pages configuration" > dist/wrangler.toml
          echo "name = \"myportfolio\"" >> dist/wrangler.toml
          echo "compatibility_date = \"2023-12-01\"" >> dist/wrangler.toml
          echo "pages_build_output_dir = \"dist\"" >> dist/wrangler.toml
          
          # Add R2 bucket configuration
          echo "" >> dist/wrangler.toml
          echo "[[r2_buckets]]" >> dist/wrangler.toml
          echo "binding = \"MY_BUCKET\"" >> dist/wrangler.toml
          echo "bucket_name = \"myportfolio\"" >> dist/wrangler.toml
          echo "preview_bucket_name = \"myportfolio\"" >> dist/wrangler.toml

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: myportfolio
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
